analyzer:
  errors:
    file_names: ignore
    non_constant_identifier_names: ignore
    unused_import: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    camel_case_types: ignore
    unused_field: ignore
    unused_local_variable: ignore
    override_on_non_overriding_member: ignore
    no_leading_underscores_for_local_identifiers: ignore
    unnecessary_import: ignore
    prefer_interpolation_to_compose_strings: ignore
    unnecessary_breaks: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    unnecessary_breaks: true
    use_key_in_widget_constructors: false