name: localize
description: A new Flutter project.

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  google_places_api_flutter: ^1.0.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.1
  http: ^1.2.2
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.6
  provider: ^6.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_in_app_messaging: ^0.8.0+8
  firebase_app_check: ^0.3.2
  info_popup: ^4.3.1
  url_launcher: ^6.3.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  encrypt: ^5.0.0
  flutter_reaction_button: ^3.0.0+3
  ionicons: ^0.2.2
  rating_summary: ^1.0.2+1
  badges: ^3.0.3
  path_provider: ^2.0.15
  firebase_admin: ^0.3.0+1
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  grpc: ^4.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  http: ^0.13.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/Logo.png
    - images/image1.jpg
    - images/Riyadh.webp
    - images/default_profile.png
    - images/Park.png
    - images/Shopping.png
    - images/Restaurant.png
    - images/children.png
    - images/place_default_image.png