name: admin_panel
description: Custom admin panel
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  localize:
    path: ../
  cloud_firestore: ^5.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  go_router: ^10.1.2
  google_fonts: ^6.1.0
  http: ^1.3.0
  fl_chart: ^0.66.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png